apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oaklbwc36-nodejs 
  janus-idp.io/tekton: oaklbwc36-nodejs
  backstage.io/kubernetes-id: oaklbwc36-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oaklbwc36-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml